spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/apartment-db
    username: admin
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/apartment-db
    user: admin
    password: password
server:
  port: 8080
