ALTER TABLE owners ALTER COLUMN surname TYPE varchar(30);
ALTER TABLE owners ALTER COLUMN surname SET NOT NULL;
ALTER TABLE owners ALTER COLUMN lastname TYPE varchar(30);
ALTER TABLE owners ALTER COLUMN lastname SET NOT NULL;
